version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
    open-pull-requests-limit: 20
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"  
    open-pull-requests-limit: 20